CREATE TABLE users (
    iduser VARCHAR(120) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    image VARCHAR(200)
);

CREATE TABLE messages(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    message VARCHAR(120) NOT NULL,
    senderId VARCHAR(120),
    receiverId VARCHAR(120),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);