CREATE TABLE users (
    id VARCHAR(120) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    image VARCHAR(200),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    message VARCHAR(128) NOT NULL,
    sender_id VARCHAR(64),
    receiver_id VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);